

# ===================================================================
# Rabbitmq properties
# ===================================================================

rabbitmq:
    hostname: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    queueName: esop
    defaultTopicExchange: esop_exchange